#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.5 (standalone edition) on Tue May 29 22:49:47 2012

import wx

# begin wxGlade: extracode
# end wxGlade


class RemoveDCPDialog(wx.Dialog):
    def __init__(self, parent, id, title):
        wx.Dialog.__init__(self, parent, id, title, size=(400, 286))    
    #def __init__(self, *args, **kwds):
        # begin wxGlade: RemoveDCPDialog.__init__
        #kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        #wx.Dialog.__init__(self, *args, **kwds)
        self.list_box_1 = wx.ListBox(self, -1, choices=[])
        self.label_1 = wx.StaticText(self, -1, "label_1")
        self.button_1 = wx.Button(self, -1, "button_1")
        self.button_2 = wx.Button(self, -1, "button_2")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RemoveDCPDialog.__set_properties
        self.SetTitle("dialog_1")
        #self.SetSize((400, 286))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RemoveDCPDialog.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.list_box_1, 2, wx.ALL | wx.EXPAND, 10)
        sizer_1.Add(self.label_1, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 3)
        sizer_2.Add(self.button_1, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_2.Add(self.button_2, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_1.Add(sizer_2,0,wx.LEFT | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 110)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade


